#!/bin/bash

if [ $# -ne 1 ]
then
    echo "Usage: example: 192.168.0"
    exit
fi

for i in `seq 1 254`
do 
ping -c 1 $1.$i >/dev/null 2> /dev/null &
done

sleep 5s
arp | grep D0:0D | awk '{print $1" "$3}' > vmacip
