#!/usr/bin/python
import logging, time, threading
import libvirt, sys, os, re, time, getopt
import libMysqlHost, libMysqlCluster, libHost

def usage():
    print """\
    -c, --clustername=ClusterName
    -h, --hostname=HostName
    clustername should be as the same as hostname\
"""

try:
    opts, args = getopt.getopt(sys.argv[1:], "c:h:", ["clustername=","hostname="])
except:
    usage()
    sys.exit()

clustername = ''
hostname = ''
for a,o in opts:
    if a in ('--clustername', '-c'):
        clustername = o
    if a in ('--hostname', '-h'):
        hostname = o
if clustername == '' or hostname == '' or clustername != hostname:
    usage()
    sys.exit()

ret = libHost.libvirt_connection(hostname)
if ret:
    libHost.cluster_register(clustername, hostname)
    libHost.host_register(hostname, clustername)
