#!/usr/bin/env python

import libvirt
import os, sys, random, re

nodes = open("/root/cloudvirt/create-nodes").read()
nodes = re.split(r"\n", nodes)
nodes.remove('')

workpath = "/var/run/cloudvirt/vm/"

for n in nodes :
    conn = libvirt.open("xen+ssh://root@%s/" % n)
    if conn == None:
        print 'Failed to open connection to the hypervisor'
	continue;

    names = os.popen("ssh %s ls %s" % (n, workpath)).read()
    names = re.split(r"\n", names)
    names.remove('')
    print names;

    for name in names:
	#if conn.lookupByName(name) != null :
	#    continue

	rand0 = random.randint(0,255)
	rand1 = random.randint(0,255)
	rand2 = random.randint(0,255)

        #mac = 'd0:0d:4f:%d:%d:%d' % (rand0, rand1, rand2)
	mac = 'd0:0d:4f:%02x:%02x:%02x' % (rand0, rand1, rand2)

        xml = open("/root/cloudvirt/libvirt.xml").read()
        xml = xml % ('vm%s' % name, 'restart', 20000000, 16, '/var/run/cloudvirt/vm/%s/root' % name, mac)
	
	tmpfname = "/tmp/tmplibvirt%s.xml" % name
	tmpfile = open(tmpfname, "w")
	tmpfile.write(xml)
	tmpfile.close()
	os.system("scp %s %s:%s/%s/libvirt.xml" % (tmpfname, n, workpath, name))	

	try:
            dom = conn.createXML(xml, 0)
	    print "Domain %s create" % name
	except:
            print "Domain %s have not been created." % (name )
