#!/usr/bin/env python

import libvirt
import os, sys, random, re, threading, time, getopt
import libshelve, libImage, libInstance

headnode = '192.168.2.1'
imgdbf = "db4img.dat"

def read_nodes(nodes_file):
    lines = open(nodes_file).read()
    lines = re.split(r"\n", lines)
    lines.remove('')
    nodes = []
    num = []
    for n in lines:
        n = re.split(r"\s", n)
        try:
            n.remove('')
        except:
            pass
        if not len(n) == 2:
            print 'Nodes File has a Wrong Format'
            usage()
            sys.exit()
        nodes.append(n[0])
        num.append(int(n[1]))
    return nodes, num

def usage():
    print \
"""    -i, --image=IMG\t\tImage ID
    -n, --nodes=FILE\t\tFile Contains Nodes and Numbers to Create Instances
    -c, --vcpus=CPUs\t\tVCPUs Number of the Virtual Machines
    -m, --mem=MEM\t\tMemory of the Virtual Machines, in Mage Byte

Run cv-describe-images to see Registered Images

Nodes File Format (on each line):
PM(Physical Machine to Create Instances) number(Number of Intances on that PM)
"""

try:
    opts, args = getopt.getopt(sys.argv[1:], "i:n:c:m:", ["image=", "nodes=", "vcpus=", "mem="])
except:
    usage()
    sys.exit()

imageid = 0
nodes_file = ''
vcpus = 0
mem = 0
for a,o in opts:
    if a in ('--image', '-i'):
        imageid = o
    if a in ('--nodes', '-n'):
        nodes_file = o
    if a in ('--vcpus', '-c'):
        vcpus = int(o)
    if a in ('--mem', '-m'):
        mem = int(o)
if imageid == 0 or nodes_file == '' or vcpus == 0 or mem == 0:
    usage()
    sys.exit()

if not libshelve.iskeyexists(imgdbf, imageid):
    print "Image Id %s doesn't existed. Run cv-describe-images to see Registered Images" % imageid
    sys.exit()

nodes, num = read_nodes(nodes_file)

imginfo = libshelve.getkey(imgdbf, imageid)
imagename = os.path.basename(imginfo['imagefilepath'])
checksum = imginfo['fastcheck']
imagesize = imginfo['imagesize']

print "Prepare VMs on:"
total = len(nodes)
for i in range(total):
    print "%s [%s VM]\t" % (nodes[i], num[i])
print "(Total %d nodes)" % (total)
print "Image ID is %s, with %d Virtual CPUs and %dM Memory." % (imageid, vcpus, mem)
print "Are You Sure (y/n)?",
v = raw_input()
if v != 'y' :
    sys.exit(1)

instance_names = libInstance.generate_instances_info(nodes, num, imageid, vcpus, mem)
print 'Instance Info Generated.. Done.'

libImage.dispatch_nv(nodes, headnode, imageid)
image_nodes = libImage.check_nodes(nodes, headnode, imageid, imagename, checksum, imagesize)
print 'Prepare to Dispatch Image.. Done.'

libImage.dispatch_image(image_nodes, headnode, imageid, imagename)
print 'Dispatch Image to Nodes.. Done.'

libImage.local_copy(nodes, num, imageid, imagename, instance_names)
print 'Nodes Image Local Copy.. Done.'

libInstance.create_instance(nodes, instance_names)
## print error info
print 'Instances Create.. Done.'

