#!/usr/bin/env python

import sys, libshelve, time

dbf = 'db4img.dat'
images = libshelve.load(dbf)

print "Image ID\tUser\tOS type\tSize\tRegister Time"
for image in images:
    info = images[image]
    uname = info['username']
    path = info['imagefilepath']
    ostype = info['imageostype']
    size = info['imagesize'] / 1024 / 1024
    regtime = time.strftime("%Y-%m-%d %H:%M:%S", info['registertime'])
    print "%s\t%s\t%s\t%sM\t%s" % (image, uname, ostype, size, regtime)
