#!/usr/bin/env python
import logging, time, threading
import libvirt, sys, os, re, libshelve, time, getopt

dbpm = 'db4pm.dat'
args = sys.argv[1:]

for host in args:
    try:
        conn = libvirt.open("xen+ssh://root@%s/" % host)
    except Exception, e:
        print "Lost Contection : " + host + " " + str(e)
        continue
    libshelve.modify(dbpm, host, {})
