#!/usr/bin/python
import logging, time, threading
import libvirt, sys, os, re, time, getopt
import libMysqlHost

args = sys.argv[1:]

hs = libMysqlHost.Hosts()
for host in args:
    ret = hs.delete([(hs.col_hostid, host)])
    if ret == 0:
        print 'Host %s has been deregistered. Done.' % host
