#!/usr/bin/env python
import logging, time, threading
import libvirt, sys, os, re, libshelve, time, getopt

dbpm = 'db4pm.dat'
args = sys.argv[1:]

for host in args:
    if libshelve.iskeyexists(dbpm, host):
        libshelve.delkey(dbpm, host) 
