#!/usr/bin/python
import sys, libHost, getopt

def usage():
    print """\
    -c, --clustername=ClusterName
    -h, --hostname=HostName
"""

try:
    opts, args = getopt.getopt(sys.argv[1:], "c:h:", ["clustername=", "hostname="])
except:
    usage()
    sys.exit()

clustername = ''
hostname = ''
for a,o in opts:
    if a in ('--clustername', '-c'):
        clustername = o
    if a in ('--hostname', '-h'):
        hostname = o
if clustername == '' or hostname == '':
    usage()
    sys.exit()

libHost.host_register(hostname, clustername)
