#!/usr/bin/python

import libInstance

f = open('cn')
instance_name = []
ins = []
for n in f.read().split('\n'):
    if len(n) == 0:
        instance_name.append(ins)
        ins = []
    else:
        ins.append(n)

f = open('cp')
host_name = []
for n in f.read().split('\n'):
    if len(n) != 0:
        host_name.append(n)

print instance_name
print host_name

libInstance.create_instance(host_name, instance_name)
