#!/usr/bin/python

import sys, time, libMysqlImages

img = libMysqlImages.Images()
images = img.select_dictlist(None)

cols = [img.col_imageid, img.col_userid, img.col_imageformat, img.col_virtual_size, img.col_chunk_count, img.col_registertime]
for key in cols:
    print key, '\t',
print
for image in images:
    for key in cols:
        print image[key], '\t',
    print
