#!/usr/bin/env python

import libvirt
import sys
from xml.dom import minidom

plist = ['192.168.2.1','192.168.2.2','192.168.2.3','192.168.2.4','192.168.2.5','192.168.2.6','192.168.2.7','192.168.2.8']
#plist = ['192.168.2.8']

for pid in plist:
    print "Physical Machine %s" % pid
    try:
        conn = libvirt.open("xen+ssh://root@%s/" % pid)
    except:
        print "Lost connection"

    print conn.getMaxVcpus('xen')
    for id in conn.listDomainsID():
        if id > 0:
            dom = conn.lookupByID(id)
            print "\tid-%d\t         %s\t       %s" % (dom.ID(), dom.name(), dom.OSType())
            x = dom.XMLDesc(0)
            ifc = minidom.parseString(x).getElementsByTagName('interface')
            print ifc[0].getElementsByTagName('mac')[0].attributes['address'].value

