#!/usr/bin/env python

import libvirt
import sys, re
from xml.dom import minidom

plist = open("/root/cloudvirt/nodelist").read()
plist = re.split(r"\n", plist)
plist.remove('')

mi = open("/root/cloudvirt/vmacip").read()
mi = re.split(r"\n", mi)
macip = {}
for i in mi:
    mil = re.split(" ", i)
    if len(mil) == 2:
	macip[mil[1].upper()] = mil[0]

for pid in plist:
    print "Physical Machine %s" % pid
    try:
        conn = libvirt.open("xen+ssh://root@%s/" % pid)
    except:
        #print "Lost connection"
	continue

    for id in conn.listDomainsID():
        if id > 0:
            dom = conn.lookupByID(id)
            x = dom.XMLDesc(0)
            ifc = minidom.parseString(x).getElementsByTagName('interface')
            mac = ifc[0].getElementsByTagName('mac')[0].attributes['address'].value.upper()
            ip = macip.get(mac)
            print "%d\t   %s\t   %s\t   %s\t   %s" % (dom.ID(), dom.name(), dom.OSType(), ip, mac)

