#!/usr/bin/env python

import sys, shelve, time

workpath = '/root/cloudvirt/'
def s2hr(s):
    ret = ''
    if s/3600 > 0:
        ret += str(s/3600) + 'h '
        s %= 3600
    if s/60 > 0:
        ret += str(s/60) + 'm '
        s %= 60
    ret += str(s) + 's'
    return ret

def shelveload():
    try:
        ret = {}
        db = shelve.open(workpath + '/db.dat', 'r')
        ret.update(db)
    finally:
        db.close()
    return ret
    
def dbsort(db, subkey):
    ret = {}
    asc = 0
    try:
        for key in db.keys():
            ret[db[key][subkey] + str(asc)] = db[key]
            asc += 1
        return ret
    except:
        return db


idb = shelveload()
print 'PM\tID\tVM\tIP\tVCpus\tMEM\tStatus\tUpdate Time'
if len(sys.argv) == 1 :
    argv = 'pm'
else:
    argv = sys.argv[1]
db = dbsort(idb, argv)
pms = db.keys()
pms.sort()
for key in pms:
    dom = db[key]
    updatetime = time.strftime("%Y-%m-%d %H:%M:%S", dom['update_time'])
    print '%s\t:%d\t%s\t%s\t%d\t%dM\t%s\t%s\t%s' % (dom['pm'], dom['id_on_pm'], dom['name'], dom['ip'], dom['vcpu'], dom['mem'], dom['status'], s2hr(dom['cputime']), updatetime)

print "Total %s VMs" % len(pms)


