#!/usr/bin/env python

import libvirt
import os, sys, random, re

nodes = open("/root/cloudvirt/nodes-create").read()
nodes = re.split(r"\n", nodes)
nodes.remove('')

print "Terminate all VMs on " + str(nodes) + ". Are you sure ?"
v = raw_input()
if v != 'y' :
   sys.exit(1)

for n in nodes :
    conn = libvirt.open("xen+ssh://root@%s/" % n)
    if conn == None:
        print 'Failed to open connection to the hypervisor'
	continue;
    
    for id in conn.listDomainsID():
        if id > 0:
	    dom = conn.lookupByID(id)
	    name = dom.name()
	    dom.destroy()
	    print "%s Terminated" % name
