#!/usr/bin/env python

import sys, os    
import logging

import resourcesmonitor 

def initlog(logfile):
    logger = logging.getLogger()
    hdlr = logging.FileHandler(logfile)
    formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
    hdlr.setFormatter(formatter)
    logger.addHandler(hdlr)
    logger.setLevel(logging.NOTSET)
    return logger

logger = initlog("/root/cloudvirt/deamon.log")

resourcesmonitor.getarping()
resourcesmonitor.getinstances(logger)

 
