#!/usr/bin/env python

import libFileCheck, os, sys, time

if len(sys.argv) == 4:
    filename = sys.argv[1]
    checksum = sys.argv[2]
    imagesize = int(sys.argv[3])
else:
    sys.exit(1)

sum = libFileCheck.fast_filechecker(filename, 0)
size = os.stat(filename).st_size

if checksum == sum and imagesize == size:
    sys.exit(0)
else:
    sys.exit(1)
