#!/usr/bin/python

import libFileCheck, os, sys, time

randomcheck_cnt = 2

if len(sys.argv) == 4:
    filename = sys.argv[1]
    checksum = sys.argv[2]
    imagesize = int(sys.argv[3])
else:
    sys.exit(1)

size = os.stat(filename).st_size
if imagesize != size:
    sys.exit(1)

chk = libFileCheck.checksum(filename)
chkok = chk.random_check(checksum, randomcheck_cnt)
if not chkok:
    sys.exit(1)

