#!/usr/bin/python

import sys, libGZip, os

orifile = sys.argv[1]
destfiles = sys.argv[2:]
#libGZip.file_decompress(orifile, destfiles, chunksize)
cmd = 'cat %s.gz.* | gzip -d ' % orifile
for df in destfiles:
    cmd += '| tee %s ' % df
cmd += ' 1>/dev/null'
os.system(cmd)

