#!/usr/bin/python

import sys

def localcopy(orifile, destfiles):
    ###check disk usage
    if orifile in destfiles:
        print 'original file is in the destiny files'
        return False
    of = open(orifile, 'rb')
    localfps = []
    for f in destfiles:
        localfps.append(open(f, 'wb'))
    bs = 1024 * 8
    while 1:
        block = of.read(bs)
        if block == "":
             break
        #read += len(block)
        for l in localfps:
            l.write(block)
    return True

orifile = sys.argv[1]
destfiles = sys.argv[2:]
localcopy(orifile, destfiles)


