#!/usr/bin/python

import sys, libMysqlInstance, time

db = libMysqlInstance.Instances()
x = db.select_dictlist(None)
print x
#for row in x:
#    print row

"""
dbimages = libSqliteImages.Images('/tmp/sqlite')
print dbimages.table_exist()
print dbimages.insert_only_value(['xxx-1', 'x', '/', 100, 'test', 2319872, ''])
print dbimages.insert([(dbimages.col_imageid, 'xxx-2')])
print dbimages.update([(dbimages.col_imageid, 'xxx-2'), (dbimages.col_ostype,'linux')], [(dbimages.col_filepath, '/tmp/x/'), (dbimages.col_filesize, 100)])
print dbimages.select([(dbimages.col_imageid, 'xxx-2')])
print dbimages.select_exist([(dbimages.col_imageid, 'xxx-3')])
x = dbimages.select_all()
print x
"""
"""
instc = libSqliteInstance.Instances()
print instc.select_all()
"""

