#!/usr/bin/env python

import libFileCheck, sys, time
s = time.time()
print libFileCheck.fast_filechecker(sys.argv[1])
e = time.time()
print e - s

s = time.time()
print libFileCheck.full_filechecker(sys.argv[1])
e = time.time()
print e - s
