#!/usr/bin/python

import libvirt
import os, sys, random, re
import libshelve

num = int(sys.argv[1])
libshelve.create('dbmac')
for n in range(num):

    rand0 = random.randint(0,255)
    rand1 = random.randint(0,255)
    rand2 = random.randint(0,255)

    mac = 'd0:0d:4f:%02x:%02x:%02x' % (rand0, rand1, rand2)
    libshelve.modify('dbmac', mac, 0)

print libshelve.load('dbmac')
