#!/usr/bin/env python

import sys, shelve, time

workpath = '/root/cloudvirt/'

def shelveload():
    ret = {}
    try:
        db = shelve.open(workpath + '/dbmac', 'r')
        ret.update(db)
    finally:
        db.close()
    return ret
    

print shelveload()
