#!/usr/bin/env python

#!/usr/bin/python

import sys
import shelve
import time

def CreateData():
    try:
        db = shelve.open('db.dat', 'c')
    finally:
        db.close()

def LoadData():
    try:
        db = shelve.open('db.dat', 'r')
        for item in db.items():
            print item
    finally:
        db.close()

def ModifyData(key, value):
    try:
        db = shelve.open('db.dat', 'w')
        db[key] = value
    finally:
        db.close()

if __name__ == '__main__':
#    CreateData()
#    ModifyData('new', sys.argv[1])
    LoadData()

